services:
  postgres:
    image: postgres:13
    container_name: redis-lock-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis1:
    image: redis:7
    container_name: redis-lock-redis1
    ports:
      - '6379:6379'

  redis2:
    image: redis:7
    container_name: redis-lock-redis2
    ports:
      - '6380:6379'

  redis3:
    image: redis:7
    container_name: redis-lock-redis3
    ports:
      - '6381:6379'

  app1:
    build: .
    container_name: redis-lock-app1
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=test
    depends_on:
      - postgres
      - redis1
      - redis2
      - redis3

  app2:
    build: .
    container_name: redis-lock-app2
    ports:
      - '3001:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=test
    depends_on:
      - postgres
      - redis1
      - redis2
      - redis3

  app3:
    build: .
    container_name: redis-lock-app3
    ports:
      - '3002:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=test
    depends_on:
      - postgres
      - redis1
      - redis2
      - redis3

volumes:
  pgdata:
